name: Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip install --system --no-deps .

      - name: Run Ruff format check on src/
        run: uv run ruff format --check src

      - name: Run Ruff linter on src/
        run: uv run ruff check src
